version: '3'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-boot11
    ports:
      - "3311:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=boot11
      - MYSQL_USER=sanus
      - MYSQL_PASSWORD=1234
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  mariadb-data:
